### ISSUE TITLE
"NameError: name 'Unicode' is not defined" when building environment from yaml

### ISSUE THREAD

**Issue by synapticarbors** [TheSnakePit/mamba#423]
I'm starting to play around with mamba and didn't want to mess with the `base` environment, so I installed mamba in its own environment along with conda. I have a simple yaml file describing the environment:

```yaml
name: test2x
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - scipy
```

If I then try to create an environment using:

```
$ mamba create --file test_env.yaml -n test2x
```

I get:

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/xyz/miniconda2/envs/mamba/lib/python3.8/site-packages/mamba/mamba.py", line 332, in install
        file_specs += specs_from_url(fpath, json=context.json)
      File "/Users/xyz/miniconda2/envs/mamba/lib/python3.8/site-packages/conda/cli/common.py", line 143, in specs_from_url
        raise CondaValueError("could not parse '%s' in: %s" %
    conda.exceptions.CondaValueError: could not parse 'name: test2x' in: test_env.yaml

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/Users/xyz/miniconda2/envs/mamba/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/Users/xyz/miniconda2/envs/mamba/lib/python3.8/site-packages/mamba/mamba.py", line 814, in exception_converter
        raise e
      File "/Users/xyz/miniconda2/envs/mamba/lib/python3.8/site-packages/mamba/mamba.py", line 808, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/Users/xyz/miniconda2/envs/mamba/lib/python3.8/site-packages/mamba/mamba.py", line 773, in _wrapped_main
        result = do_call(args, p)
      File "/Users/xyz/miniconda2/envs/mamba/lib/python3.8/site-packages/mamba/mamba.py", line 667, in do_call
        exit_code = create(args, parser)
      File "/Users/xyz/miniconda2/envs/mamba/lib/python3.8/site-packages/mamba/mamba.py", line 568, in create
        install(args, parser, 'create')
      File "/Users/xyz/miniconda2/envs/mamba/lib/python3.8/site-packages/mamba/mamba.py", line 333, in install
        except Unicode:
    NameError: name 'Unicode' is not defined

`$ /Users/xyz/miniconda2/envs/mamba/bin/mamba create --file test_env.yaml -n test2x`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=mamba
                CONDA_EXE=/Users/xyz/miniconda2/bin/conda
             CONDA_PREFIX=/Users/xyz/miniconda2/envs/mamba
           CONDA_PREFIX_1=/Users/xyz/miniconda2
           CONDA_PREFIX_2=/Users/xyz/miniconda2/envs/x
    CONDA_PROMPT_MODIFIER=(mamba)
         CONDA_PYTHON_EXE=/Users/xyz/miniconda2/bin/python
               CONDA_ROOT=/Users/xyz/miniconda2/envs/mamba
              CONDA_SHLVL=3
                     PATH=/Users/xyz/miniconda2/envs/mamba/bin:/Users/xyz/miniconda2/condabin:/U
                          sers/xyz/.cargo/bin:/Users/xyz/local/bin/nvim-osx64/bin:/Applications/
                          MacVim.app/Contents/bin:/Users/xyz/local/bin:/usr/local/bin:/usr/bin:
                          /bin:/usr/sbin:/sbin:/usr/local/bin:/usr/texbin:/opt/X11/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /Users/xyz/miniconda2/envs/mamba
            shell xyzel : 3
       user config file : /Users/xyz/.condarc
 populated config files : /Users/xyz/.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __osx=10.14.6
       base environment : /Users/xyz/miniconda2/envs/mamba  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /Users/xyz/miniconda2/envs/mamba/pkgs
                          /Users/xyz/.conda/pkgs
       envs directories : /Users/xyz/miniconda2/envs/mamba/envs
                          /Users/xyz/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.3 requests/2.24.0 CPython/3.8.5 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

If I don't specify the environment name on the command line I get:

```
CondaValueError: The target prefix is the base prefix. Aborting.
```

although maybe that has something to do with not installing `mamba` in the `base` environment. I assumed this was ok given the development instructions in the README: "If you build mamba in a different environment than base, you must also install conda in that environment".

**Comment by wolfv** [comment]
yes, it doesn't work because mamba has to be in the base environment. Sorry, we'll need to clarify the README.

**Comment by wolfv** [comment]
although this looks like there might be something buggy in mamba.

**Comment by wolfv** [comment]
okay I think we've got multiple issues at the same time.
mamba should import this Unicode class / error.

but the environment file you're using -- I think it needs to be used with `mamba env create -f ...` right?

**Comment by synapticarbors** [comment]
@wolfv -- you're correct. I made a mistake and should have used `mamba env create -f`. That works.
